### ISSUE TITLE
Adder example panic

### ISSUE THREAD

**Issue by jsimonetti** [goadesign/examples#2]
Following the README for the adder example to the letter does not produce the same result:

```
jeroen@develop ~/dev/src/local/goatest % go get github.com/goadesign/examples/adder
jeroen@develop ~/dev/src/local/goatest % cd ~/dev/src/github.com/goadesign/examples/adder
jeroen@develop ..rc/github.com/goadesign/examples/adder (git)-[master] % go generate
app
app/contexts.go
app/controllers.go
app/hrefs.go
app/media_types.go
app/user_types.go
main.go
operands.go
test
test/operands.go
client
client/adder-cli
client/adder-cli/main.go
client/adder-cli/commands.go
client/client.go
client/operands.go
client/hrefs.go
swagger
swagger/swagger.json
swagger/swagger.yaml
swagger/swagger.go
go generate  10.33s user 0.85s system 138% cpu 8.083 total
jeroen@develop ..rc/github.com/goadesign/examples/adder (git)-[master] % go build
jeroen@develop ..rc/github.com/goadesign/examples/adder (git)-[master] % ./adder&
[1] 21172
2016/04/24 09:55:50 [INFO] mount ctrl=Operands action=Add route=GET /add/:left/:right
2016/04/24 09:55:50 [INFO] mount file name=swagger/swagger.json route=GET /swagger.json
2016/04/24 09:55:50 [INFO] listen transport=http addr=:8080
jeroen@develop ..rc/github.com/goadesign/examples/adder (git)-[master] % curl http://localhost:8080/
2016/04/24 09:56:01 http: panic serving 127.0.0.1:48626: runtime error: index out of range
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc820010780)
        /usr/lib/go-1.6/src/net/http/server.go:1389 +0xc1
panic(0x840c40, 0xc82000a090)
        /usr/lib/go-1.6/src/runtime/panic.go:426 +0x4e9
github.com/goadesign/goa.(*adapter).logit(0xc8200bbcc0, 0x8cfea8, 0x7, 0xc820010880, 0x8, 0x8, 0x7fbc4216e700)
        /home/jeroen/dev/src/github.com/goadesign/goa/logging.go:95 +0x8af
github.com/goadesign/goa.(*adapter).Info(0xc8200bbcc0, 0x8cfea8, 0x7, 0xc820010880, 0x8, 0x8)
        /home/jeroen/dev/src/github.com/goadesign/goa/logging.go:50 +0x58
github.com/goadesign/goa.LogInfo(0x7fbc4216e798, 0xc82014a3f0, 0x8cfea8, 0x7, 0xc820010880, 0x8, 0x8)
        /home/jeroen/dev/src/github.com/goadesign/goa/logging.go:107 +0x126
github.com/goadesign/goa/middleware.LogRequest.func1.1(0x7fbc4216e798, 0xc82014a3f0, 0x7fbc4216fd40, 0xc8200e6c30, 0xc82014e000, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/goadesign/goa/middleware/log_request.go:33 +0x777
github.com/goadesign/goa/middleware.RequestID.func1.1(0x7fbc4216e798, 0xc82014a3c0, 0x7fbc4216fd40, 0xc8200e6c30, 0xc82014e000, 0x0, 0x0)
        /home/jeroen/dev/src/github.com/goadesign/goa/middleware/request_id.go:50 +0x40f
github.com/goadesign/goa.New.func2(0x7fbc4216fd40, 0xc8200e6c30, 0xc82014e000, 0x0)
        /home/jeroen/dev/src/github.com/goadesign/goa/service.go:97 +0x539
github.com/goadesign/goa.(*mux).HandleNotFound.func1(0x7fbc4216fd40, 0xc8200e6c30, 0xc82014e000)
        /home/jeroen/dev/src/github.com/goadesign/goa/mux.go:67 +0x42
github.com/dimfeld/httptreemux.(*TreeMux).ServeHTTP(0xc8200602a0, 0x7fbc4216fd40, 0xc8200e6c30, 0xc82014e000)
        /home/jeroen/dev/src/github.com/dimfeld/httptreemux/router.go:190 +0x2d1
github.com/goadesign/goa.(*mux).ServeHTTP(0xc82000bb30, 0x7fbc4216fd40, 0xc8200e6c30, 0xc82014e000)
        /home/jeroen/dev/src/github.com/goadesign/goa/mux.go:83 +0x42
net/http.serverHandler.ServeHTTP(0xc820010700, 0x7fbc4216fd40, 0xc8200e6c30, 0xc82014e000)
        /usr/lib/go-1.6/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820010780)
        /usr/lib/go-1.6/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/lib/go-1.6/src/net/http/server.go:2137 +0x44e
curl: (52) Empty reply from server
```

I am completely new to GOA and relatively new to GO, so I have no idea how to fix this.

**Comment by jsimonetti** [comment]
Appologies for this issue. IT was due to Old package Versions still in my gopath. Removing them and rerunning Go get fixed IT.
